name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag foam-language-server:$(date +%s)
    - name: Push the Docker image to Hub
      run: docker login -u foamscience -p ${DOCKER_TOKEN} && docker push -a
